function [G] = g(x, y, hyp,i)

logsigma = hyp(1);
logtheta = hyp(2);

if i == 0 || i == 1
    
    gg = @(x,y) (1/2).*exp(1).^(logsigma+(-2).*logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x.^2+y.^2)).*(10.*exp(1).^(2.*logtheta+(1/2).*exp(1) ...
        .^((-1).*logtheta).*x.^2).*(1+5.*exp(1).^logtheta)+(-2).*exp(1).^( ...
        exp(1).^((-1).*logtheta).*x.*y).*(exp(1).^logtheta.*((-1)+exp(1) ...
        .^logtheta.*(6+25.*exp(1).^logtheta))+(x+(-1).*y).^2)+5.*exp(1).^( ...
        2.*logtheta+(1/2).*exp(1).^((-1).*logtheta).*y.^2).*(2+10.*exp(1) ...
        .^logtheta+exp(1).^((1/2).*(logtheta+exp(1).^((-1).*logtheta).* ...
        x.^2)).*((-10).*exp(1).^((1/2).*logtheta)+(2.*pi).^(1/2).*((2+5.* ...
        x).*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*x)+5.*((-1).*x+y).* ...
        erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*(x+(-1).*y))+(2+5.*y).* ...
        erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*y)))));
    
    G = bsxfun(gg,x,y');
    
elseif i==2
    
    gg = @(x,y) (1/4).*exp(1).^(logsigma+(-3).*logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x.^2+y.^2)).*((-2).*exp(1).^(exp(1).^((-1).*logtheta) ...
        .*x.*y).*(50.*exp(1).^(4.*logtheta)+2.*exp(1).^(2.*logtheta).*(1+ ...
        3.*(x+(-1).*y).^2)+(-5).*exp(1).^logtheta.*(x+(-1).*y).^2+(x+(-1) ...
        .*y).^4)+10.*exp(1).^(2.*logtheta+(1/2).*exp(1).^((-1).*logtheta) ...
        .*x.^2).*(10.*exp(1).^(2.*logtheta)+(-2).*exp(1).^logtheta.*y+ ...
        y.^2)+5.*exp(1).^(2.*logtheta+(1/2).*exp(1).^((-1).*logtheta).* ...
        y.^2).*(2.*(10.*exp(1).^(2.*logtheta)+(-2).*exp(1).^logtheta.*x+ ...
        x.^2)+exp(1).^((1/2).*(3.*logtheta+exp(1).^((-1).*logtheta).*x.^2) ...
        ).*((-20).*exp(1).^((1/2).*logtheta)+(2.*pi).^(1/2).*((2+5.*x).* ...
        erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*x)+5.*((-1).*x+y).*erf( ...
        2.^(-1/2).*exp(1).^((-1/2).*logtheta).*(x+(-1).*y))+(2+5.*y).*erf( ...
        2.^(-1/2).*exp(1).^((-1/2).*logtheta).*y)))));
    
    G = bsxfun(gg,x,y');
    
end

end

