function K_ff = k_ff(x, y, hyp,i)

logsigma = hyp(1);
logtheta = hyp(2);
alpha = hyp(3);
beta = 1;

if i == 0 || i == 1
    
    kk = @(x,y) exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^(1/2).*(exp(1) ...
        .^logtheta).^(1/2).*pi.^(-1/2).*(2.^alpha.*(exp(1).^logtheta).^(( ...
        -1).*alpha).*gamma((1/2)+alpha).*kummer((1/2)+alpha,( ...
        1/2),(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+beta.*( ...
        beta.*exp(1).^((-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).* ...
        pi.^(1/2)+(-1).*2.^(1+(1/2).*alpha).*(exp(1).^logtheta).^((-1/2).* ...
        alpha).*cos((1/2).*alpha.*pi).*gamma((1/2).*(1+alpha)).* ...
        kummer((1/2).*(1+alpha),(1/2),(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)));
    
    K_ff = real(bsxfun(kk,x,y'));
    
elseif i == 2
    
    kk = @(x,y) (1/2).*exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^(1/2).*(exp( ...
        1).^logtheta).^(-1/2).*(beta.*exp(1).^((-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2).*(beta.*(x+(-1).*y).^2+2.^(1+(1/2).* ...
        alpha).*(exp(1).^logtheta).^((-1/2).*alpha).*pi.^(-1/2).*cos((1/2) ...
        .*alpha.*pi).*gamma((1/2).*(1+alpha)).*(alpha.*exp(1).^logtheta.* ...
        kummer((-1/2).*alpha,(1/2),(1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)+(-1).*(1+alpha).*(x+(-1).*y).^2.* ...
        kummer((-1/2).*alpha,(3/2),(1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)))+2.^alpha.*(exp(1).^logtheta).^((-1).* ...
        alpha).*pi.^(-1/2).*gamma((1/2)+alpha).*((-2).*alpha.*exp(1) ...
        .^logtheta.*kummer((1/2)+alpha,(1/2),(-1/2).*exp(1).^(( ...
        -1).*logtheta).*(x+(-1).*y).^2)+(1+2.*alpha).*(x+(-1).*y).^2.* ...
        kummer((3/2)+alpha,(3/2),(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)));
    
    K_ff = real(bsxfun(kk,x,y'));
    
elseif i == 3
    
    kk = @(x,y) 2.^((1/2).*alpha).*exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^( ...
        1/2).*(exp(1).^logtheta).^((1/2)+(-1).*alpha).*pi.^(-1/2).*(2.^(( ...
        1/2).*alpha).*gamma((1/2)+alpha).*kummer((1/2)+alpha,( ...
        1/2),(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).*(log(2)+( ...
        -1).*log(exp(1).^logtheta)+psi(0,(1/2)+alpha))+beta.*(exp(1) ...
        .^logtheta).^((1/2).*alpha).*gamma((1/2).*(1+alpha)).* ...
        kummer((1/2).*(1+alpha),(1/2),(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2).*((-1).*cos((1/2).*alpha.*pi).*(log(2)+ ...
        (-1).*log(exp(1).^logtheta)+psi(0,(1/2).*(1+alpha)))+pi.* ...
        sin((1/2).*alpha.*pi))+2.^((1/2).*alpha).*gamma((1/2)+alpha).* ...
        kummer_a((1/2)+alpha,(1/2),(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+(-1).*beta.*(exp(1) ...
        .^logtheta).^((1/2).*alpha).*cos((1/2).*alpha.*pi).*gamma((1/2).*( ...
        1+alpha)).*kummer_a((1/2).*(1+alpha),( ...
        1/2),(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2));
    
    K_ff = real(bsxfun(kk,x,y'));
    
elseif i == 4
    
    kk = @(x,y) 2.*exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^(1/2).*(exp(1) ...
        .^logtheta).^(1/2).*pi.^(-1/2).*(beta.*exp(1).^((-1/2).*exp(1).^(( ...
        -1).*logtheta).*(x+(-1).*y).^2).*pi.^(1/2)+(-1).*2.^((1/2).*alpha) ...
        .*(exp(1).^logtheta).^((-1/2).*alpha).*cos((1/2).*alpha.*pi).* ...
        gamma((1/2).*(1+alpha)).*kummer((1/2).*(1+alpha),(1/2), ...
        (-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2));
    
    K_ff = real(bsxfun(kk,x,y'));
    
end

