function K_uf = k_uf(xx, yy, hyp,i)

logsigma = hyp(1);
logthetat = hyp(2);
logthetax = hyp(3);
alpha = hyp(4);

t = xx(:,1);
x = xx(:,2);
s = yy(:,1);
y = yy(:,2);

if i == 0 || i == 1
    
    K_uf = exp(1).^(logsigma+(-1).*logthetat+(-2).*logthetax+(-1/2).*exp(1) ...
        .^((-1).*logthetat).*bsxfun(@minus,t,s').^2+(-1/2).*exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^2).*(exp(1).^(2.*logthetax).*bsxfun(@minus,t,s')+ ...
        exp(1).^logthetat.*(exp(1).^logthetax+(-1).*bsxfun(@minus,x,y').^2).*alpha);
    
elseif i == 2
    
    K_uf = (1/2).*exp(1).^(logsigma+(-2).*logthetat+(-2).*logthetax+(-1/2).* ...
        exp(1).^((-1).*logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^2).*(-bsxfun(@minus,t,s')).*(exp(1).^(2.*logthetax) ...
        .*(2.*exp(1).^logthetat+(-1).*(-bsxfun(@minus,t,s')).^2)+exp(1).^(logthetat+ ...
        logthetax).*(-bsxfun(@minus,t,s')).*alpha+(-1).*exp(1).^logthetat.*(-bsxfun(@minus,t,s')).*...
        bsxfun(@minus,x,y').^2.*alpha);
    
elseif i == 3
    
    K_uf = (-1/2).*exp(1).^(logsigma+(-1).*logthetat+(-3).*logthetax+(-1/2).* ...
        exp(1).^((-1).*logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^2).*(exp(1).^(2.*logthetax).*(-bsxfun(@minus,t,s')) ...
        .*bsxfun(@minus,x,y').^2+exp(1).^logthetat.*(2.*exp(1).^(2.*logthetax)+( ...
        -5).*exp(1).^logthetax.*bsxfun(@minus,x,y').^2+bsxfun(@minus,x,y').^4).*alpha);
    
elseif i == 4
    
    K_uf = exp(1).^(logsigma+(-2).*logthetax+(-1/2).*exp(1).^((-1).* ...
        logthetat).*bsxfun(@minus,t,s').^2+(-1/2).*exp(1).^((-1).*logthetax).*...
        bsxfun(@minus,x,y').^2).*(exp(1).^logthetax+(-1).*bsxfun(@minus,x,y').^2);
    
end

