function K_ff = k_ff(xx, yy, hyp,i)

logsigma = hyp(1);
logthetat = hyp(2);
logthetax = hyp(3);
lambda = hyp(4);
alpha = hyp(5);

t = xx(:,1);
x = xx(:,2);
s = yy(:,1);
y = yy(:,2);

if i == 0 || i == 1
    
    K_ff = exp(1).^(logsigma+(-2).*logthetat+(-4).*logthetax+(-1/2).*exp(1) ...
        .^((-1).*logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^2).*(exp(1).^(4.*logthetax).*(exp(1) ...
        .^logthetat+exp(1).^(2.*logthetat).*lambda.^2+(-1).*(-bsxfun(@minus,t,s')) ...
        .^2)+2.*alpha.*exp(1).^(2.*(logthetat+logthetax)).*lambda.*(exp(1) ...
        .^logthetax+(-1).*bsxfun(@minus,x,y').^2)+alpha.^2.*exp(1).^(2.*logthetat) ...
        .*(3.*exp(1).^(2.*logthetax)+(-6).*exp(1).^logthetax.*bsxfun(@minus,x,y') ...
        .^2+bsxfun(@minus,x,y').^4));
    
elseif i == 2
    
    K_ff = (1/2).*exp(1).^(logsigma+(-2).*logthetat+(-4).*logthetax+(-1/2).* ...
        exp(1).^((-1).*logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^2).*(exp(1).^(logthetat+4.*logthetax).*(( ...
        -2)+lambda.^2.*(-bsxfun(@minus,t,s')).^2)+5.*exp(1).^(4.*logthetax).*...
        (-bsxfun(@minus,t,s')).^2+2.*alpha.*exp(1).^(logthetat+3.*logthetax).*lambda.*...
        (-bsxfun(@minus,t,s')).^2+(-1).*exp(1).^((-1).*logthetat+4.*logthetax).*...
        (-bsxfun(@minus,t,s')).^4+alpha.*exp(1).^(logthetat+2.*logthetax).*(-bsxfun(@minus,t,s')).^2.*( ...
        3.*alpha+(-2).*lambda.*bsxfun(@minus,x,y').^2)+(-6).*alpha.^2.*exp(1).^( ...
        logthetat+logthetax).*(-bsxfun(@minus,t,s')).^2.*bsxfun(@minus,x,y').^2+alpha.^2.* ...
        exp(1).^logthetat.*(-bsxfun(@minus,t,s')).^2.*bsxfun(@minus,x,y').^4);
    
elseif i == 3
    
    K_ff = (1/2).*exp(1).^(logsigma+(-2).*logthetat+(-4).*logthetax+(-1/2).* ...
        exp(1).^((-1).*logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^2).*(2.*alpha.*exp(1).^(2.*logthetat+ ...
        logthetax).*lambda.*((-2).*exp(1).^(2.*logthetax)+5.*exp(1) ...
        .^logthetax.*bsxfun(@minus,x,y').^2+(-1).*bsxfun(@minus,x,y').^4)+alpha.^2.*exp(1) ...
        .^(2.*logthetat).*((-12).*exp(1).^(2.*logthetax)+39.*exp(1) ...
        .^logthetax.*bsxfun(@minus,x,y').^2+(-14).*bsxfun(@minus,x,y').^4+exp(1).^((-1).* ...
        logthetax).*bsxfun(@minus,x,y').^6)+exp(1).^(3.*logthetax).*(exp(1) ...
        .^logthetat+exp(1).^(2.*logthetat).*lambda.^2+(-1).*(-bsxfun(@minus,t,s')) ...
        .^2).*bsxfun(@minus,x,y').^2);
    
elseif i == 4
    
    K_ff = 2.*exp(1).^(logsigma+(-2).*logthetax+(-1/2).*exp(1).^((-1).* ...
        logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).*logthetax).*...
        bsxfun(@minus,x,y').^2).*(exp(1).^(2.*logthetax).*lambda+alpha.*(exp(1) ...
        .^logthetax+(-1).*bsxfun(@minus,x,y').^2));
    
elseif i == 5
    
    K_ff = 2.*exp(1).^(logsigma+(-4).*logthetax+(-1/2).*exp(1).^((-1).* ...
        logthetat).*(-bsxfun(@minus,t,s')).^2+(-1/2).*exp(1).^((-1).*logthetax).*...
        bsxfun(@minus,x,y').^2).*(exp(1).^(2.*logthetax).*lambda.*(exp(1).^logthetax+( ...
        -1).*bsxfun(@minus,x,y').^2)+alpha.*(3.*exp(1).^(2.*logthetax)+(-6).*exp( ...
        1).^logthetax.*bsxfun(@minus,x,y').^2+bsxfun(@minus,x,y').^4));
    
end

end

